@echo off
setlocal

echo [Windows] Downloading dependencies...

curl -s -L "https://raw.githubusercontent.com/z-libs/zerror.h/main/zerror.h" -o zerror.h
curl -s -L "https://raw.githubusercontent.com/z-libs/zstr.h/main/zstr.h" -o zstr.h
curl -s -L "https://raw.githubusercontent.com/z-libs/zfile.h/main/zfile.h" -o zfile.h
curl -s -L "https://raw.githubusercontent.com/z-libs/zthread.h/main/zthread.h" -o zthread.h

if exist "..\znet.h" (
    echo [Windows] Copying znet.h...
    copy /Y "..\znet.h" "." >nul
) else (
    echo [Error] Could not find ..\znet.h
    goto :error
)

echo [Windows] Compiling zhttpd.exe...
gcc zhttpd_std.c -o zhttpd.exe -std=c11 -lws2_32 -O2 -DZHTTPD_DEBUG

if %errorlevel% neq 0 goto :error

echo [Windows] Compiling Modules...
if not exist "modules" mkdir modules

echo # zhttpd module configuration (Auto-generated by build.bat) > modules.conf

for %%f in (modules\*.c) do (
    echo    - %%~nf.dll
    
    gcc -shared -o modules\%%~nf.dll %%f -O2 -std=c11 ^
        -lws2_32 ^
        -DZNET_IMPLEMENTATION ^
        -DZTHREAD_IMPLEMENTATION ^
        -DZSTR_IMPLEMENTATION ^
        -DZFILE_IMPLEMENTATION ^
        -DZERROR_IMPLEMENTATION ^
        -DZTIME_IMPLEMENTATION
        
    if %errorlevel% neq 0 goto :error
    
    echo load modules/%%~nf.dll >> modules.conf
)

echo [Windows] Build Success! Run zhttpd.exe to start.
goto :eof

:error
echo [Windows] Build Failed.
exit /b 1
